server:
  port: 8089


eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
  instance:
    hostname: owg-eureka-server
  server:
    eviction-interval-timer-in-ms: 5000
